[build]
  command = "npm run build"
  publish = "dist"

[context.deploy-preview]
  command = "npm run build-preview"
  
[context.production.environment]
  HUGO_VERSION = "0.34"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.34"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.34"  
